return {
  --   {
  --     "neovim/nvim-lspconfig",
  --     opts = {
  --       servers = {
  --         tsserver = {
  --           enabled = false,
  --         },
  --       },
  --     },
  --   },
  --   {
  --     "williamboman/mason-lspconfig.nvim",
  --     opts = {
  --       handlers = {
  --         function(server_name)
  --           if server_name == "tsserver" then
  --             return
  --           end
  --         end,
  --       },
  --     },
  --   },
  --   {
  --     "pmizio/typescript-tools.nvim",
  --     dependencies = { "nvim-lua/plenary.nvim", "neovim/nvim-lspconfig" },
  --     opts = {
  --       on_attach = function(_, bufnr)
  --         vim.keymap.set(
  --           "n",
  --           "gsd",
  --           "<cmd>TSToolsGoToSourceDefinition<cr>",
  --           { buffer = bufnr, desc = "Go To Source Definition GG" }
  --         )
  --       end,
  --     },
  --   },
}
